language: java

jdk:
  - openjdk16
  - openjdk15
  - openjdk11
  - openjdk8

cache:
  directories:
    - $HOME/.m2

script:
  # build using mybatis latest released version
  - ./mvnw clean verify -Dlog.level.thymeleaf.config=info
  # test using mybatis 3.4.x line
  - ./mvnw test -Dmybatis.version=3.4.6 -Dlog.level.thymeleaf.config=info
  # build using mybatis 3.5.x snapshot
  - ./mvnw clean verify -Dmybatis.version=$(./travis/get_latest_version.sh 3.5) -Dlog.level.thymeleaf.config=info

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - ./travis/after_success.sh

env:
  global:
  - secure: OaMDXm8ttk8ruvBRz7o5MCKGSjfm42wS8c+jcxqciyfvgb9ThI77SEnzs/4Qey7bPGyD9IxXGbmREqf5MVxVitFIQltOJOhhHCMi73ltHCn1tY68PUhHp5KOaLzDoltsMUfgBOD4LrzKa8+xMbGMC3I+squmKCd5AfyVuA+2P8/FZfCFbUtIHDJdlAZfl1LBaATWVWFO6e0+SIgTv8szfcALkDwrfzLIGateC/awHAbPwYtk/YChd9P5zrTcXLKrWpDS44jeOkkuZ6jR641GzeFTA6EpklE0DMo4vP65qJJrYMFzL6QvbVOCCWXamMhxo6+6Qlvp0XQQYWatfRV41+OLHpl38hWoPPX8oJil2dXjQ9Ef0AJYNfpVEm6pYYgqDRV81eEEW2OSmMjWVub2yTkTzHST5R45sLXYhFcXYlIxnSz6UGhdgCtmiOCtGHEaLb2hyIDCt4OapURvxQL9OwEMj8YgjcKPa87dT0icf6/uArOyXodW3OGjDkOGuSWialGYId9Qgvrgqr07xRKz/SAjrWfgNgkJho3zrT7K5OMV67ncMpN312bjbIMbe2Y9ROR2EDPG3reqewUgvU4D5ai39/ri8bgopbUOfnU7X8ofudxD2AFAM8T80EoksfG7qFt6vxwNEjomO1bu/5gCBPntqX0i4HKY5XhZ5TIdufQ=
  - secure: atFoUdYmt2jJ0irBFdn0Dpz9j84sELyNRPlPInrWDMfXBTrqSLpgFw3vDrshRwVMKWyylJ5VjVxHp7YXHxmUdS6UDDPETKnmVmQMNxhXTMQJZzMLeKSnjnJjfB7eDG6Fud/WhWY7ivxgu6NgEJG+hEuVNYyjvxJ+T3g1dg9WvVHMw4JveDf6vgUAgS85+nZuQLxdrKZrAeQtLtFnxjGJBjdbmlQA+TiLGAaL/r5AT9sg4mjJcLT6tH+006bABMqGTkEfuvisUOjiY3Ys+K8EsT1IoL4cJq3dEuhNrvE673KSOKvYQYGj3VsaZnBCtQCQIU/baymwXOFOzRR5WRA7qCwToECK9WbMpY4pBIY06sfcgBGRsF6Ch1zQa1YdNO0xizM1Yj/1lQC7mujf3kb6bwUlvtW738YF3ynC+IvygKU85hQ314M1twwiZJJHmngVJu/Fuy5YVctbpEFJnd1CzWWWrjfaVQUbA7DTlqtck5pyc13jA4SbSEJEbdI1+oGpoBF95E30gTSNqg6wW7t4Fq5XKYPG5JNYUuYNqG0+sHehjeCt/L3rezLWOHnK13M/pyeCXHiMLtnWzUGmXIe0O0g2SYyrab0yy6Psgr0JZD/32E4j70hRdLW63aId5uTaPI3J1FY7VmPMIVi37rzysiJdbrOoyUaO9yYIv3QOPPQ=
